import type { Dossier } from "@prisma/client"

/**
 * Crée un dossier factice pour les tests.
 * Tous les champs sont à null/défaut sauf ceux passés en override.
 */
export function makeDossier(overrides: Partial<Dossier> = {}): Dossier {
  return {
    id: "test-id",
    tenantId: "tenant-1",
    cabinetId: "cabinet-1",
    raisonSociale: "TEST DOSSIER",
    activite: null,
    nomContact: null,
    emailContact: null,
    telephoneContact: null,
    siren: null,
    formeJuridique: null,
    regimeFiscal: null,
    typeMission: null,
    logicielComptable: null,
    paie: true,
    commentaireInterne: null,
    collaborateurPrincipalId: null,
    dateClotureExercice: null,
    datePrevueArreteBilan: null,
    dateBilanPersonnalisee: false,
    dateArreteBilan: null,
    commentaireBilan: null,
    statutCourantSaisie: null,
    statutManquantSaisie: null,
    noteManquantSaisie: null,
    statutRevisionFaite: null,
    statutOdInventaire: null,
    statutManquantRevision: null,
    noteManquantRevision: null,
    statutEtatsFinanciers: null,
    statutLiasseFiscale: null,
    statutSignatureAssocie: null,
    statutEnvoiClient: null,
    statutTeledeclaration: null,
    statut2572: null,
    statutDas2: null,
    statutVerifEnvoi: null,
    statutAgo: null,
    regimeTva: null,
    dateLimiteTva: null,
    tvaSuivi: null,
    taxeFonciereNote: null,
    suiviCfe: null,
    suiviCvae: null,
    suiviTvs: null,
    taxeFonciereDetail: null,
    acomptesIs: null,
    soldeIs: null,
    acompteIsN1: null,
    acompteCvae06: null,
    acompteCvae09: null,
    soldeCvae: null,
    statut2561: null,
    statut: "ACTIF",
    raisonArchivage: null,
    dateArchivage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    ...overrides,
  }
}
